import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My Cinema Intro!</a>
        </h1>

        <p className={styles.description}>
          Get started by signing up{' '}
          <code className={styles.code}>pages/signup.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Home Theater &rarr;</h2>
            <p>Find in-depth information about My Cinema Intro, and our plans to amaze your family and friends with a custom tailored experience to your Home Theater.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Cameo  &rarr;</h2>
            <p>Learn about My Cinema Intro and our plans to integrate Cameo voice and video stingers!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Streaming Integration &rarr;</h2>
            <p>Start your Movie night with an intro experience sure to leave your family and friends speechless. Connect My Cinema Intro to your Home Theater dashboard and use the same streaming platform for all of your Home Theater movie choices.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Early Access - Lifetime Membership NFT &rarr;</h2>
            <p>
              Stand above the crowd with a limited edition NFT to signify your lifetime Membership, Owning the My Cinema Intro NFT establishes your access to the platform as long as the NFT is owned and held.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/mycinemaintro-favicon.svg" alt="My Cinema Intro Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
